# Generated by Django 4.1.2 on 2023-03-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_bajasalumnos_remove_leavereportstudent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bajasalumnos',
            options={'ordering': ['nombre_alumno']},
        ),
    ]
