# Generated by Django 4.1.2 on 2023-03-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_bajasalumnos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajasalumnos',
            name='motivos_abandono',
            field=models.TextField(null=True, verbose_name='Motivos de abandono'),
        ),
    ]
