# Generated by Django 4.1.2 on 2023-03-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_bajasalumnos_motivos_abandono'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajasalumnos',
            name='t_d',
            field=models.CharField(choices=[('1', 'Temporal'), ('2', 'Definitiva')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
