# Generated by Django 4.1.2 on 2023-03-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_bajasalumnos_t_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajasalumnos',
            name='t_d',
            field=models.CharField(choices=[('1', 'Temporal'), ('2', 'Definitiva')], max_length=2, verbose_name='Tipo de baja'),
        ),
        migrations.AlterField(
            model_name='bajasalumnos',
            name='tipo_baja',
            field=models.CharField(choices=[('1', 'A SU FAMILIA NO LE GUSTABA LA CARRERA'), ('2', 'ACTITUD DE PROFESORES'), ('3', 'AMBIENTE ESTUDIANTIL'), ('4', 'BAJA ACADÉMICA POR DESEMPEÑO ESCOLAR'), ('5', 'BAJA ACADÉMICA POR REPROBACIÓN'), ('6', 'BAJA ACADÉMICA POR DESEMPEÑO ESCOLAR'), ('7', 'CAMBIO DE PAÍS'), ('8', 'CAMPO LABORAL DIFÍCIL'), ('9', 'DESEMPEÑO ACADÉMICO INADECUADO'), ('10', 'DIFICULTAD ACADÉMICA POR LA MODALIDAD EN LÍNEA'), ('11', 'DIFICULTAD DE RELACIONARSE CON COMPAÑEROS/MAESTROS'), ('12', 'DIFICULTAD EN LAS MATERIAS'), ('13', 'ESTADO CIVIL'), ('14', ' ESTADO DE ÁNIMO'), ('15', 'FALTA DE HABILIDADES DE APRENDIZAJE'), ('16', 'HORARIOS COMPLICADOS'), ('17', 'INFLUENCIA DE PADRES/AMIGOS EN LA ELECCIÓN DE CARRERA'), ('18', 'LUGAR DE DOMICILIO'), ('19', 'MÉTODOS DE ENSEÑANZA'), ('20', 'MOTIVOS PERSONALES'), ('21', 'NO ERA MI VOCACIÓN'), ('22', 'PÉRDIDA DE INTERÉS POR LA CARRERA'), ('23', 'PERFIL DE LA CARRERA'), ('24', 'PROBLEMAS PERSONALES'), ('25', 'REPROBACIÓN'), ('26', 'SER ACEPTADO EN OTRA UNIVERSIDAD'), ('27', 'SITUACIÓN ECONÓMICA COMPLICADA'), ('28', 'TENER QUE TRABAJAR'), ('29', 'OTRO')], max_length=2, verbose_name='Motivo de baja'),
        ),
    ]
